blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('fullpost/<int:id>', views.fullpost, name='fullpost'),
    path('create_post', views.create_post, name='create_post'),
    path('update_post/<int:id>', views.update_post, name='update_post'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('delete_post/<int:pk>', views.delete_post, name='delete_post'),
    path('like_post/<int:id>', views.like_post, name='like_post'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('fullpost/<int:id>/<int:commentid>',
         views.commentReply, name='comments'),
    path('editcomment/<int:id>/<int:commentid>',
         views.editComment, name='editcomment'),
    path('deletecomment/<int:id>/<int:commentid>',
         views.deleteComment, name='deletecomment'),
    path('editreply/<int:id>/<int:commentid>/<int:replyid>',
         views.editReply, name='editreply'),
    path('deletereply/<int:id>/<int:commentid>/<int:replyid>',
         views.deleteReply, name='deletereply'),
]
urlpatterns += [
    path('v1/', views.ListpostView.as_view(), name='listposts'),
    path('v1/post/<int:pk>/', views.PostDetailAPIView.as_view(), name='detail-post'),
    path('v1/post/', views.CreatePostAPIView.as_view(), name='create-post'),
    path('v1/delete/post/<int:pk>/',
         views.DeletePostAPIView.as_view(), name='delete-post'),
    path('v1/post/<int:pk>/comments/',
         views.ListCommentView.as_view(), name='viewComments'),
    path('v1/post/<int:pk>/like/',
         views.LikePostAPIView.as_view(), name='like-post'),
    path('v1/post/<int:postid>/comment/',
         views.CreateCommentAPIView.as_view(), name='createComments'),
    path('v1/comment/<int:pk>', views.CommentDetailAPIView.as_view(),
         name='detail-comment'),
    path('v1/delete/comment/<int:pk>/',
         views.DeleteCommentAPIView.as_view(), name='delete-comment'),
    path('auth/', include('rest_auth.urls')),
    path('auth/register/', include('rest_auth.registration.urls')),
]
urlpatterns += [
    path('v2/', views.GPostListAPIView.as_view(), name='generic_postList'),
    path('v2/post/<int:pk>/', views.GPostDetailAPIView.as_view(),
         name='generic-detail-post'),
    path('v2/post/', views.GPostCreateAPIView.as_view(), name='create-post'),
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

schema_view = get_schema_view(
   openapi.Info(
      title="Blog API",
      default_version='v1',
      description="Blog Application",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="fiacregiraneza@gmail"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.IsAuthenticated),
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('swagger.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import datetime

class Post(models.Model):
    title = models.CharField(max_length=200,null=False)
    content = models.TextField(max_length=3000, help_text='Enter a content of the a post')
    image = models.ImageField(upload_to='uploads', default='../../static/img/3.jpg')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,verbose_name='created_by')
    created_on = models.DateField(default=datetime.date.today)
    
    class Meta:
        ordering = ['-id']

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.id)])

class Comment(models.Model):
    content = models.TextField(max_length=2000, help_text='Enter your comment', verbose_name='Put your comment here')
    post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True,verbose_name='commented_on')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,verbose_name='commented_by')

    class Meta:
        ordering = ['-id']
        
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.content})'
        
class Like(models.Model):
    post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True,verbose_name='Liked_on')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,verbose_name='Liked_by')
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id}'

class CommentLike(models.Model):
    comment=models.ForeignKey('Comment', on_delete=models.SET_NULL, null=True,verbose_name='Liked on comment')
    user= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,verbose_name='Liked_by')
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id}'

class CommentReply(models.Model):
    content = models.TextField(max_length=2000, help_text='Enter your comment', verbose_name='Enter your reply here')
    comment = models.ForeignKey('Comment', on_delete=models.SET_NULL, null=True,verbose_name='replied_on')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,verbose_name='commented_by')

    class Meta:
        ordering = ['id']
        
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.content})'

blog/forms.py
from django import forms
from .models import Comment, CommentReply, Post
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User


# creating a form
class Postform(forms.ModelForm):
    
	# create meta class
	class Meta:
		# specify model to be used
		model = Post

		# specify fields to be used
		fields = [
			"title",
			"content",
            "image"
		]

		
class Updateform(forms.ModelForm):
 
	# create meta class
	class Meta:
		# specify model to be used
		model = Post

		# specify fields to be used
		fields = [
			"title",
			"content",
            "image"
		]

class createComment(forms.ModelForm):

	# create meta class
	class Meta:
		# specify model to be used
		model = Comment

		# specify fields to be used
		fields = [
			"content"
		]


class CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','email','password1','password2']

class LoginForm(AuthenticationForm):
	class Meta:
		model=User
		fields=['username','password']

class commentReplyForm(forms.ModelForm):

	# create meta class
	class Meta:
		# specify model to be used
		model = CommentReply

		# specify fields to be used
		fields = [
			"content"
		]

blog/views.py
import time
from django.conf import settings
from django.shortcuts import render
from blog.permissions import IsOwnerOrReadOnly

from blog.serializer import CommentSerializer, DisplayPostSerializer, LoginSerializer, PostSerializer
from .models import CommentReply, Like, Post, Comment
from .forms import CreateUserForm, LoginForm, Postform, Updateform, commentReplyForm, createComment
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from rest_framework import views, response, decorators, parsers, permissions, authentication,filters,generics,status


def logout_required(function=None, logout_url='index'):
    actual_decorator = user_passes_test(
        lambda u: not u.is_authenticated,
        login_url=logout_url
    )
    if function:
        return actual_decorator(function)
    return actual_decorator

@login_required(login_url='login')
def index(request):
    """View function for home page of site."""
    context={}
    posts = Post.objects.all()
    # for post in posts:
    #     print('hi')
    likes=Like.objects.filter(user=request.user)
    if likes:
        print('hi ',likes)
    context = {
        'posts': posts,
        'likes':likes
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

@login_required(login_url='login')
def create_post(request):
    context = {}
    form = Postform(request.POST, request.FILES)
    if request.method =='POST':
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            response = redirect('/')
            return response
        else:
            form = Postform(request.POST, request.FILES)
    else:
        form = Postform()

    context['form'] = form
    return render(request, 'create_post.html', context=context)

@login_required(login_url='login')
def update_post(request, id):
    context = {}
    instance = get_object_or_404(Post, id=id)
    form = Updateform(request.POST, request.FILES,instance=instance)
    if(Post.objects.filter(author=request.user,id=id)):
        if form.is_valid():
            form.instance.created_on = time.strftime(r"%Y-%m-%d", time.localtime())
            form.save()
            response = redirect('/dashboard')
            return response
        else:
            form = Updateform(request.POST or None, instance=instance)
        context['form'] = form
        return render(request, 'update_post.html', context=context)
    else:
        messages.info(request,'401 Not Authorized')
        return render(request, 'errors.html')

@login_required(login_url='login')
def dashboard(request):
    posts = Post.objects.filter(author=request.user)

    context = {
        'posts': posts
    }
    return render(request, 'datatable.html', context=context)

@login_required(login_url='login')
def delete_post(request,pk):
    if(Post.objects.filter(author=request.user)):
        record=Post.objects.get(id=pk)
        record.delete()
        response = redirect('/dashboard')
        return response
    else:
        return redirect('index')

@login_required(login_url='login')
def fullpost(request, id):
    post = Post.objects.get(id=id)
    comment_form = createComment(request.POST or None)
    print(request.POST)
    if comment_form.is_valid():
        comment_form.instance.post = post
        comment_form.instance.user = request.user
        comment_form.save()
        comment_form = createComment()
    context = {
        'post': post,
        'comment_form': comment_form
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'fullpost.html', context=context)

@login_required(login_url='login')
def like_post(request, id):
    post = Post.objects.get(id=id)
    checkuser = Like.objects.filter(user=request.user,post=post)
    liked=False
    if not checkuser:
        Like.objects.create(
            post=post,
            user=request.user)
        liked=True
    else:
        checkuser.delete()
        liked=False
    context={
        'likes':Like.objects.filter(post=post).count(),
        'liked':liked
    }
    return render(request,'like.html',context=context)

def register(request):
    form = CreateUserForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('login')
    else:
        form = CreateUserForm()

    context = {'form':form}

    return render(request,'registration/register.html',context)

@logout_required()
def login_view(request):
    context={}
    # if request.user:
        # return redirect('index')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard')
        else:
            messages.info(request,'username or password is incorrect')
            form = LoginForm()
            context = {'form':form}
    else:
        form = LoginForm()
        context = {'form':form}

    return render(request,'registration/login.html',context)

def logout_view(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
def commentReply(request, id,commentid):
    post = Post.objects.get(id=id)
    comments=Comment.objects.get(id=commentid)
    comment_form = commentReplyForm(request.POST or None)
    if comment_form.is_valid():
        comment_form.instance.comment = comments
        comment_form.instance.user = request.user
        comment_form.save()
        comment_form = commentReplyForm()
        return redirect('comments',id=id,commentid=commentid)
    context = {
        'post': post,
        'choosenComment':comments,
        'comment_form': comment_form
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'comments.html', context=context)

@login_required(login_url='login')
def editComment(request, id,commentid):
    post = Post.objects.get(id=id)
    comments=Comment.objects.get(id=commentid)
    instance = get_object_or_404(Comment, id=commentid)
    comment_form = createComment(request.POST or None,instance=instance)
    if(comments.user!=request.user):
        return redirect('fullpost',id=id)
    if comment_form.is_valid():
        comment_form.save()
        comment_form = createComment()
        return redirect('fullpost',id=id)
    context = {
        'post': post,
        'choosenComment':comments,
        'comment_form': comment_form
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'editComment.html', context=context)

@login_required(login_url='login')
def deleteComment(request, id,commentid):
  if(Comment.objects.filter(user=request.user)):
        record=Comment.objects.get(id=commentid)
        record.delete()
        return redirect('fullpost',id=id)
  else:
       return redirect('fullpost',id=id)


@login_required(login_url='login')
def editReply(request, id,commentid, replyid):
    post = Post.objects.get(id=id)
    comments=Comment.objects.get(id=commentid)
    instance = get_object_or_404(CommentReply, id=replyid)
    comment_form = commentReplyForm(request.POST or None,instance=instance)
    chosenreply= CommentReply.objects.get(id=replyid)
    if comment_form.is_valid():
        comment_form.save()
        comment_form = commentReplyForm()
        return redirect('comments',id=id,commentid=commentid)
    context = {
        'post': post,
        'choosenComment':comments,
        'chosenreply':chosenreply,
        'comment_form': comment_form
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'editReply.html', context=context)

@login_required(login_url='login')
def deleteReply(request, id,commentid, replyid):
  if(CommentReply.objects.filter(user=request.user)):
        record=CommentReply.objects.get(id=replyid)
        record.delete()
        return redirect('comments',id=id,commentid=commentid)
  else:
       return redirect('comments',id=id,commentid=commentid)
##################################################################




'''class based views'''
class ListpostView(views.APIView):
    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        posts = Post.objects.all()
        content=[]
        for post in posts:
            print(post.author)
            postAppend={}
            if post.author:
               postAppend['author']=post.author.username
            postAppend['title']=post.title
            postAppend['content']=post.content
            comments=[]
            for comment in Comment.objects.filter(post=post):
                commentfd={}
                commentfd['user']=comment.user.username
                commentfd['content']=comment.content
                comments.append(commentfd)
            postAppend['comment']=comments
            postAppend['likes']=Like.objects.filter(post=post).count()
            content.append(postAppend)
        print(content)
        # serializer = PostSerializer(posts, many=True)
        return response.Response(content)


class PostDetailAPIView(views.APIView):
    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, pk):
        post = get_object_or_404(Post, id=pk)
        serializer = PostSerializer(post, many=False)
        return response.Response(serializer.data)

    def put(self, request, pk):
        instance = get_object_or_404(Post, id=pk)
        if(instance.author==request.user):

blog/templates/comments.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <link rel="apple-touch-icon" type="image/png"
        href="https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png" />
    <meta name="apple-mobile-web-app-title" content="CodePen">

    <link rel="shortcut icon" type="image/x-icon"
        href="https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico" />

    <link rel="mask-icon" type="image/x-icon"
        href="https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg"
        color="#111" />


    <title>{{post.title}}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"
        type="text/javascript"></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <script>
        window.console = window.console || function (t) { };
    </script>



    <script>
        if (document.location.search.match(/type=embed/gi)) {
            window.parent.postMessage("resize", "*");
        }
    </script>


</head>

<body translate="no">
    {% include 'header.html' %}
    {% load crispy_forms_tags %}
    <br> <br><br>
    <svg display="none" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <defs>
            <symbol id="icon-bubble" viewBox="0 0 1024 1024">
                <title>bubble</title>
                <path class="path1"
                    d="M512 224c8.832 0 16 7.168 16 16s-7.2 16-16 16c-170.464 0-320 89.728-320 192 0 8.832-7.168 16-16 16s-16-7.168-16-16c0-121.408 161.184-224 352-224zM512 64c-282.784 0-512 171.936-512 384 0 132.064 88.928 248.512 224.256 317.632 0 0.864-0.256 1.44-0.256 2.368 0 57.376-42.848 119.136-61.696 151.552 0.032 0 0.064 0 0.064 0-1.504 3.52-2.368 7.392-2.368 11.456 0 16 12.96 28.992 28.992 28.992 3.008 0 8.288-0.8 8.16-0.448 100-16.384 194.208-108.256 216.096-134.88 31.968 4.704 64.928 7.328 98.752 7.328 282.72 0 512-171.936 512-384s-229.248-384-512-384zM512 768c-29.344 0-59.456-2.24-89.472-6.624-3.104-0.512-6.208-0.672-9.28-0.672-19.008 0-37.216 8.448-49.472 23.36-13.696 16.672-52.672 53.888-98.72 81.248 12.48-28.64 22.24-60.736 22.912-93.824 0.192-2.048 0.288-4.128 0.288-5.888 0-24.064-13.472-46.048-34.88-56.992-118.592-60.544-189.376-157.984-189.376-260.608 0-176.448 200.96-320 448-320 246.976 0 448 143.552 448 320s-200.992 320-448 320z">
                </path>
            </symbol>
            <symbol id="icon-star" viewBox="0 0 1024 1024">
                <title>star</title>
                <path class="path1"
                    d="M1020.192 401.824c-8.864-25.568-31.616-44.288-59.008-48.352l-266.432-39.616-115.808-240.448c-12.192-25.248-38.272-41.408-66.944-41.408s-54.752 16.16-66.944 41.408l-115.808 240.448-266.464 39.616c-27.36 4.064-50.112 22.784-58.944 48.352-8.8 25.632-2.144 53.856 17.184 73.12l195.264 194.944-45.28 270.432c-4.608 27.232 7.2 54.56 30.336 70.496 12.704 8.736 27.648 13.184 42.592 13.184 12.288 0 24.608-3.008 35.776-8.992l232.288-125.056 232.32 125.056c11.168 5.984 23.488 8.992 35.744 8.992 14.944 0 29.888-4.448 42.624-13.184 23.136-15.936 34.88-43.264 30.304-70.496l-45.312-270.432 195.328-194.944c19.296-19.296 25.92-47.52 17.184-73.12zM754.816 619.616c-16.384 16.32-23.808 39.328-20.064 61.888l45.312 270.432-232.32-124.992c-11.136-6.016-23.424-8.992-35.776-8.992-12.288 0-24.608 3.008-35.744 8.992l-232.32 124.992 45.312-270.432c3.776-22.56-3.648-45.568-20.032-61.888l-195.264-194.944 266.432-39.68c24.352-3.616 45.312-18.848 55.776-40.576l115.872-240.384 115.84 240.416c10.496 21.728 31.424 36.928 55.744 40.576l266.496 39.68-195.264 194.912z">
                </path>
            </symbol>
        </defs>
    </svg>
    <div class="blog-container">
        <div class="blog-header">
            <div class="blog-cover" style=" 
            background: url('../../media/{{post.image }}');
            background-size: cover;
            border-radius: 5px 5px 0 0;
            height: 35rem;
            box-shadow: inset rgba(0, 0, 0, 0.2) 0 64px 64px 16px;">
                <div class="blog-author">
                    <h3>{{post.author}}</h3>
                </div>
            </div>
        </div>

        <div class="blog-body">
            <div class="blog-title">
                <h1><a href="#">{{post.title}}</a></h1>
            </div>
            <div class="blog-summary">
                <p>{{post.content}}</p>
            </div>
            <div class="blog-tags">
                <ul>
                    <li><a href="#">css</a></li>
                    <li><a href="#">web design</a></li>
                    <li><a href="#">codepen</a></li>
                    <li><a href="https://twitter.com/russbeye">twitter</a></li>
                </ul>
            </div>
        </div>

        <div class="blog-footer">
            <ul>
                <li class="published-date">published on {{post.created_on}}</li>
                <li class="comments" onclick="">
                    <a href="{% url 'fullpost' post.id %}"><svg class="icon-bubble">
                            <use xlink:href="#icon-bubble"></use>
                        </svg><span class="numero">{{post.comment_set.all.count}}</span></a>
                </li>
                <li class="shares"> <a href="{% url 'like_post' post.id %}">
                        <svg class="icon-star">
                            <use xlink:href="#icon-star"></use>
                        </svg><span class="numero">{{post.like_set.all.count}}</span>
                    </a>
                </li>
            </ul>
            <br>

            <div>
                <div>
                    {% for comment in post.comment_set.all%}
                    {% if comment.id == choosenComment.id %}
                    <p>posted by: {{comment.user}}</p>
                    <p>{{comment.content}} <br>
                    <div style="margin-left: 5vw;">
                        {% if comment.commentreply_set.all %}
                        {% for com in comment.commentreply_set.all%}
                        <p>replied by: {{com.user}}</p>
                        <p>{{com.content}}</p>
                        {% if com.user == user %}
                        <a href="{% url 'editreply' post.id  comment.id com.id %}">edit</a> &nbsp; &nbsp;
                        <a href="{% url 'deletereply' post.id  comment.id com.id %}">delete</a>
                        {% endif %}
                        <hr>
                        {%endfor%}
                        {% endif %}
                        <form action="{% url 'comments' post.id  comment.id %}" method="post">
                            {% csrf_token %}
                            <table>
                                {{ comment_form|crispy }}
                            </table>
                            <input type="submit" class="btn btn-secondary" value="SUBMIT"><br>
                        </form>
                    </div>
                    <br><br>
                    <hr>
                    {%else%}
                    <p>posted by: {{comment.user}}</p>
                    <p>{{comment.content}}</p> <br>
                    {% if comment.commentreply_set.all %}
                    <a href="{% url 'comments' post.id  comment.id %}">show replies</a>
                    {% else %}
                    <a href="{% url 'comments' post.id  comment.id %}">reply</a>
                    {% endif %}
                    <hr>
                    <br>
                    {%endif%}
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>



    <script type="text/javascript" src="//use.typekit.net/wtt0gtr.js"></script>
    <script type="text/javascript">try { Typekit.load(); } catch (e) { }</script>
    <script
        src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-1b93190375e9ccc259df3a57c1abc0e64599724ae30d7ea4c6877eb615f89387.js"></script>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

</body>

</html>

blog/templates/datatable.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <!-- FONT AWESOME STYLE  -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" />
    <!-- DATATABLE STYLE  -->
    <link href="{% static 'js/dataTables/dataTables.bootstrap.css' %}" rel="stylesheet" />
    <!-- CUSTOM STYLE  -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

</head>

<body>
    {% include 'header.html' %}
    <br><br>
    <div class="row" style="margin-top: 5rem;">
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading" style="display: flex; flex-direction: row;">
                    <h4 style="text-align: center; margin-left: 40vw;">Post List</h4>
                    <button class="btn btn-secondary" title="add new post"
                        style="margin-left: 5vw; justify-self: flex-end;"><a href="/create_post" style="text-decoration: none;
                        color: #fff;">+</a></button>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Post Title</th>
                                    <th>Author</th>
                                    <th>likes</th>
                                    <th>Created at</th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            {% if posts %}
                            <tbody>
                                {% for post in posts%}
                                <tr class="odd gradeX">
                                    <td>{{post.title}}</td>
                                    <td>{{post.author}}</td>
                                    <td class="center">{{post.like_set.all.count}}</td>
                                    <td class="center">{{post.created_on}}</td>
                                    <td class="center">

                                        <button class="btn btn-primary" data-toggle="modal"
                                            data-target="#myModal-{{post.id}}"><i class="fa fa-eye "></i> View
                                            Post</button>

                                        <a href="{% url 'update_post' post.id %}" class="btn btn-primary"><i
                                                class="fa fa-edit "></i> Edit</a>
                                        <a href="{% url 'delete_post' post.id%}" class="btn btn-danger"><i
                                                class="fa fa-trash"></i> Delete</a>



                                    </td>
                                </tr>

                                <div class="modal fade" id="myModal-{{post.id}}" tabindex="-1" role="dialog"
                                    aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-hidden="true">&times;</button>
                                                <h4 class="modal-title" id="myModalLabel">{{post.title}}</h4>
                                            </div>
                                            <div class="modal-body">
                                                {{post.content}}
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default"
                                                    data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                    </div>
                </div>
                <!-- End Modals-->

                {% endfor %}

                </tbody>
                {% else %}
                <p>no post created yet</p>
                {% endif %}
                </table>
            </div>

        </div>
    </div>

    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
    <!-- BOOTSTRAP SCRIPTS  -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!-- CUSTOM SCRIPTS  -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>